### ISSUE TITLE
Schema select disappears when sub-schema inside ArrayEditor gets deleted

### ISSUE THREAD

**Issue by milesleif** [Putaitu/putaitu-cms#265]

**Comment by milesleif** [comment]
@mrzapp I stumbled over this by reproducing https://github.com/HashBrownCMS/hashbrown-cms/issues/236  - this behavior is new to the current version (not happening in 1.0). 

To reproduce: 

1. create a Field Base schema that is using the ArrayEditor and „richText“ as allowed schemas, configured to at least one item minimum
2. create a Content Base schema that uses an ArrayEditor and the Field Base schema above as well as at least one other random Field Base schema as allowed schemas (so that we get a dropdown for selecting the desired schema)
3. Add content with the Content Base schema above and add an item to this new page
4. select the above created richText-using schema
5. delete the first richtText-Editor with a click on the top right x
6. watch the schema-selection disappear

![dont-leave-me-this-way](https://user-images.githubusercontent.com/1314903/53012982-cc35a900-3444-11e9-9177-8ba8632f6698.gif)

**Comment by milesleif** [comment]
addition 1: this also happens when an image is assigned to a medieReference-schema (after closing the upload / select media dialog the schema select disappears)

addition 2: schema-select reappears when new components are added to the page

assumption: this has something to do with the update cycle of the ui

**Comment by mrzapp** [comment]
Should be solved now, I also polished the nested array items look a bit

**Comment by milesleif** [comment]
@mrzapp works! :) 

Unfortunately there is still a little side effect. I'd open another ticket but it's tightly bound to the process, so I hope you're okay with me trying to squeeze it in here. 

When adding an item into the richtText-array via the plus-button, the width of the parent container collapses so that the items don't span over the full width anymore. 

![dont-squish-me-please](https://user-images.githubusercontent.com/1314903/53722716-76aac480-3e66-11e9-8602-8c888ee2da6e.gif)

I figured that this has something to do with the class list changing on the field-editor-array (the one with the `data-guid`-attribute. 

Before adding:
![before-adding](https://user-images.githubusercontent.com/1314903/53722575-2a5f8480-3e66-11e9-890a-99f76b9acd37.jpg)

After adding: 
![after-adding](https://user-images.githubusercontent.com/1314903/53722581-321f2900-3e66-11e9-9562-9c4d760ab5ca.jpg)


The class `editor__field__value` is taken away from the element and thus it's losing its properties, including `flex-grow: 1` which makes it span across the full width in the first place. 

Since this might have a lot of implications in terms of other classes / class-combinations I'd rather give this back to you again before manually changing styles here.

**Comment by mrzapp** [comment]
@milesleif OK, yeah this was a bit tricky. The class `editor__field__value` is something the FieldEditor itself doesn't know about, as it's assigned by the ContentEditor. However, if the FieldEditor needs to re-render, the ContentEditor wasn't listening for that event (the "ready" event).

I've added a callback to the "ready" event to re-add the class whenever the FieldEditor is done rendering.

**Comment by milesleif** [comment]
@mrzapp unfortunatley this does not seem to fix it as I still run into the behavior captured above. I also noticed collapsed widths on solo richTexteditors. 

Maybe we don't need to approach that too docmatically. I guess a simple `flex-grow: 1` on `.field-editor` would do the trick. Can you think of any particular problems this could produce? Or to rephrase: do you think that could be a valid solution?

**Comment by mrzapp** [comment]
@milesleif My bad, I forgot to add the same fix to the ArrayEditor itself
